name: WorkflowDispatch

on:
  workflow_dispatch:

jobs:
  mutation-testing:
    uses: saleazer/GitHubWorkflows/.github/workflows/StrykerJS.yml@main
    with:
      node-version: "20.11.1"
    secrets: inherit

