name: FleetWebClient

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "18.19"

jobs:
  buildClient:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 1

    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        
    - name: Set diff
      id: changed-files
      run: echo "DIFF=$(git diff --name-only -r ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} | xargs)" >> $GITHUB_OUTPUT

    - name: Get diff
      run: echo "The diff is ${{ steps.changed-files.outputs.DIFF }}"

    # - name: Setup Node
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ env.NODE_VERSION }}

    # - name: npm install
    #   run: npm i


    # - name: Run Stryker
    #   run: npx stryker run --mutate "src\app\reactive-form\reactive-form.component.ts"

    # - name: Upload Stryker Report
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: stryker-report
    #     path: reports/mutation/mutation.html      
