name: FleetWebClient

on:
  push:
    branches: ["master", "lets-learn-yml-0815"]
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "18.17"

jobs:
  buildClient:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install
      run: npm i

    - name: stryker install and run
      run: |
        npm i -g stryker-cli
        stryker run --mutate "src\app\reactive-form\reactive-form.component.ts"

    # - name: stryker install
    #   run: npm i -g stryker-cli

    # - name: stryker run
    #   run: stryker run --mutate "src\app\reactive-form\reactive-form.component.ts"

