name: FleetWebClient

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "18.19"

jobs:
  buildClient:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install
      run: npm i

    - name: Get changed files
      id: changed-files
      uses: actions/github-script@v6
      with:
        script: |
          const { data: files } = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });

          const filteredFiles = files
            .map(file => file.filename)
            .filter(filename => filename.endsWith('.component.ts'))
            .join(', ');

          core.setOutput('files', filteredFiles);
  
    - name: Get diff
      run: echo "The diff is ${{ steps.changed-files.outputs.files }}"

    - name: Run Stryker
      if: ${{ steps.changed-files.outputs.files != '' }}
      run: npx stryker run --mutate "${{ steps.changed-files.outputs.files }}"

    - name: Read mutation report
      id: read-mutation-report
      if: ${{ steps.changed-files.outputs.files != '' }}
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const reportContent = fs.readFileSync('reports/mutation/mutation.html', 'utf8');
          core.setOutput('report', reportContent);

    - name: Comment Mutation Results
      if: ${{ steps.changed-files.outputs.files != '' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const reportContent = steps.read-mutation-report.outputs.report;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Here is the mutation report:\n\n${reportContent}`
          });

    # - name: Upload Stryker Report
    #   if: ${{ steps.changed-files.outputs.files != '' }}
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: stryker-report
    #     path: reports/mutation/mutation.html      
