name: FleetWebClient

on:
  push:
    branches: ["master", "lets-learn-yml-0815"]
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "18.19"

jobs:
  buildClient:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install
      run: npm i

    # - name: Install Stryker locally
    #   run: npm install --save-dev @stryker-mutator/core

    - name: Run Stryker
      run: npx stryker run --mutate "src\app\reactive-form\reactive-form.component.ts"

    - name: Upload Stryker Report
      uses: actions/upload-artifact@v2
      with:
        name: stryker-report
        path: reports/mutation/mutation.html      
