name: FleetWebClientScheduled

on:
  schedule:
    - cron: '18 23 * * 1'

env:
  ENVIRONMENT_PATH: src/assets/environment.json
  DIST_PATH: dist
  NODE_VERSION: "20.9.0"

jobs:
  buildClient:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install
      run: npm i
      
    - name: Run Stryker
      run: npx stryker run | tee stryker-output.txt

    - name: Upload Stryker Report
      uses: actions/upload-artifact@v4
      with:
        name: stryker-report
        path: reports/mutation/mutation.html 
