name: LetsLearnCI/CD

on:
  pull_request:
    branches: ["master"]

env:
  ENVIRONMENT_PATH: src/assets/environment.json
  DIST_PATH: dist
  NODE_VERSION: "20.9.0"
  INCREMENTAL_PATH: reports/stryker-incremental.json

jobs:
  buildClient:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install
      run: npm i
        
    # - name: Install Temporary Dependencies
    #   run: npm install axios adm-zip

    # - name: Download and Extract Artifact
    #   run: node .github/workflows/download-artifact.js
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     OWNER: ${{ github.repository_owner }}
    #     REPO: ${{ github.event.repository.name }}
    #     WORKFLOW_NAME: LetsLearnCI/CD
    #     ARTIFACT_NAME: stryker-incremental

    - name: Run Stryker
      run: |
          npx stryker run --incremental

    - name: Upload Stryker Incremental Report
      uses: actions/upload-artifact@v4
      with:
        name: stryker-incremental
        path: ${{ env.INCREMENTAL_PATH }}
  
    - name: Upload Stryker Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: stryker-coverage
        path: reports/mutation/mutation.html