name: LetsLearnCI/CD

on:
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "20.9.0"
  INCREMENTAL_PATH: reports/stryker-incremental.json
  FILESTOSTRYKE_COUNT: 0
  FILESTOSTRYKE: ''

jobs:
  buildClient:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    # - name: npm install
    #   run: npm i
        
    - name: Install Temporary Dependencies
      run: npm install axios adm-zip @actions/core @actions/github

    - name: Download and Extract Incremental File
      run: node .github/workflows/download-artifact.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
        ARTIFACT_NAME: stryker-incremental

    # - name: Determine Files to Stryke
    #   run: node .github/workflows/determine-files.js
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     FILESTOSTRYKE_COUNT: ${{ env.FILESTOSTRYKE_COUNT }}

    # - name: Run Stryker
    #   run: |
    #     if [ -f /home/runner/work/lets-learn-angular/lets-learn-angular/.github/workflows/extracted_artifact/stryker-incremental.json ]; then
    #       echo "Incremental artifact found, continuing Stryker incremental run."
    #       if [ "$FILESTOSTRYKE" != '' ]; then
    #         echo "Running Stryker incremental with $FILESTOSTRYKE."
    #         npx stryker run --incremental --incrementalFile /home/runner/work/lets-learn-angular/lets-learn-angular/.github/workflows/extracted_artifact/stryker-incremental.json
    #       else
    #         echo "No component files were defined to stryke. Unable to run Stryker incremental."
    #       fi
    #     else
    #       echo "No incremental artifact round, running Stryker as initial incremental run."
    #       if [ "$FILESTOSTRYKE" != '' ]; then
    #         echo "Running Stryker with $FILESTOSTRYKE."
    #         npx stryker run --incremental --incrementalFile /home/runner/work/lets-learn-angular/lets-learn-angular/.github/workflows/extracted_artifact/stryker-incremental.json
    #       else
    #         echo "No component files were defined to stryke. Unable to run Stryker."
    #       fi
    #     fi
    #     echo "INCREMENTAL_PATH=/home/runner/work/lets-learn-angular/lets-learn-angular/.github/workflows/extracted_artifact/stryker-incremental.json" >> $GITHUB_ENV

    # - name: Upload Stryker Incremental Report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: stryker-incremental_${{ env.FILESTOSTRYKE_COUNT }}
    #     path: ${{ env.INCREMENTAL_PATH }}
  
    # - name: Upload Stryker Coverage Report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: stryker-coverage
    #     path: reports/mutation/mutation.html